FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY pom.xml .
RUN apt-get update && apt-get install -y maven \
    && rm -rf /var/lib/apt/lists/*

# Maven im PATH sicherstellen
ENV PATH="/usr/share/maven/bin:${PATH}"
