spring.application.name=flenski

server.address=0.0.0.0
server.port=8081

spring.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:8081}

# Database configuration
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.ai.mistralai.api-key=${MISTRAL_API_KEY}
spring.ai.model.embedding=mistral
spring.ai.mistralai.embedding.options.model=mistral-embed

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.root=INFO
logging.level.com.flenski.controller=INFO
logging.level.com.flenski.service=INFO
logging.level.com.flenski.service.QueryService=DEBUG

# Sparse vector vocab file configuration
vocabulary.file.path=data/vocabulary.json

spring.ai.vectorstore.qdrant.initialize-schema=false
spring.ai.vectorstore.qdrant.host=${QDRANT_HOST}
spring.ai.vectorstore.qdrant.port=${QDRANT_PORT}
spring.ai.vectorstore.qdrant.collection=${QDRANT_COLLECTION}
spring.ai.vectorstore.qdrant.collection-test=${QDRANT_COLLECTION_TEST:test}
spring.ai.vectorstore.qdrant.use_tls=${QDRANT_USE_TLS}
spring.ai.vectorstore.qdrant.api_key=${QDRANT_API_KEY}

flenski.indexing.QueueService.queueBatchSize=10
flenski.indexing.documentSourceDirectoryName=data/scraped/ratsversammlung
flenski.indexing.documentQueuedDirectoryName=data/scraped/ratsversammlung/queued

flenski.indexing.DocumentBuilderService.chunkSize=356
flenski.indexing.DocumentBuilderService.maxNumChunks=1024

flenski.query.parameters.queryMode = HYBRID
flenski.query.parameters.timeBoost.enable = true
flenski.query.parameters.timeBoost.midPoint = 0.5f
flenski.query.parameters.timeBoost.scale = 30
flenski.query.parameters.timeBoost.dateField = "source_date_time"
flenski.query.parameters.titleBoost.enable = true
flenski.query.parameters.titleBoost.factor = 0.5
flenski.query.parameters.limit = 100
flenski.query.parameters.maxLimit = 100
flenski.query.parameters.collection = "production"
flenski.query.parameters.sparseSearchScoreThreshold = 0.5f
flenski.query.parameters.denseSearchScoreThreshold = 0f

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
