/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/Answer.vue')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Datenschutzerklaerung: typeof import('./src/components/Datenschutzerklaerung.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DateRange: typeof import('./src/components/DateRange.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Select: typeof import('primevue/select')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Snippet: typeof import('./src/components/Snippet.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
